### ISSUE TITLE
Opening HABmin generates hundreds of errors in the openHAB log

### ISSUE THREAD

**Issue by GertKonemann** [cdjackson/HABmin#206]
When I open the webpage http://192.168.XXX.YYY:8080/habmin/index.html, hundreds of these messages are written in openhab.log."

2015-01-12 22:04:15.749 [ERROR] [i.h.s.p.PersistenceModelHelper] - Can't open model file 'myopenhab'
2015-01-12 22:04:15.749 [ERROR] [i.h.s.p.PersistenceModelHelper] - Can't open model file 'myopenhab'
2015-01-12 22:04:15.749 [ERROR] [i.h.s.p.PersistenceModelHelper] - Can't open model file 'myopenhab'
2015-01-12 22:04:15.749 [ERROR] [i.h.s.p.PersistenceModelHelper] - Can't open model file 'myopenhab'

I have 2 persistance services (rrd4j and db4o), but HABmin gives me a choice of 3. It adds myopenhab. The same happens with HABmin2.
To be sure it has nothing todo with the my.openhab.org service, I removed that binding, but that makes no difference. Can you explain what the myopenhab choice in HABmin is and how I can avoid these messages.

Gert

**Comment by cdjackson** [comment]
I’ve no idea - it’s trying to open a myopenhab.persist file - but I’ve no idea why. Habmin should get a list of all the resource services, and then open up the .persist files. I’m not sure why it would be opening this file, or why it would be looping so fast.  I’m not sure how to debug this though - is there any chance you can record what’s going on in the chrome (or firebug) debugger if you enable debugging tools?=

**Comment by GertKonemann** [comment]
Chris,

 

Thank you for your quick reaction. This picture shows the myopenhab choice in HABmin. As I have zero experience with web development, it is a big hurdle for me to do something with the Chrome development tools. I have found a javascript console. Is that what you mean ? If so I have to study the documentation before I can do something useful with it. If I push the refresh button on this page 200 to 300 messages are written in the log. I will spend a few hours to see if I can find the place in the code where the message is written and where I can place a breakpoint.

 

Gert

 



 

 

 

Van: Chris Jackson [mailto:notifications@github.com] 
Verzonden: dinsdag 13 januari 2015 0:14
Aan: cdjackson/HABmin
CC: GertKonemann
Onderwerp: Re: [HABmin] Opening HABmin generates hundreds of errors in the openHAB log (#206)

 

I’ve no idea - it’s trying to open a myopenhab.persist file - but I’ve no idea why. Habmin should get a list of all the resource services, and then open up the .persist files. I’m not sure why it would be opening this file, or why it would be looping so fast. I’m not sure how to debug this though - is there any chance you can record what’s going on in the chrome (or firebug) debugger if you enable debugging tools?=

**Comment by petrklus** [comment]
I saw the same with mqtt persistence - the problem is probably that I've got the binding installed but not using the persistence (and thus the file does not exist).

I will see if I can reproduce this consistently but apart from log file entries, I did not see any harmful effects of this.

**Comment by cdjackson** [comment]
Hi Gert,
It's a bit difficult to explain I think :( One option if you like is I could remotely connect to your computer - I did this last weekend using TeamViewer - I'd never used it before but someone using HABmin2 had an issue and suggested it and it worked really well...

If you're not too keen on that, I'll try and talk you through it, but it's maybe less simple - let me now what you'd prefer...

Chris

**Comment by GertKonemann** [comment]
Hi Chris,

 

I have found a workaround for this problem. I have put a dummy myopenhab.persist file in \openhab\configurations\persistence and now the error messages are gone. I do not understand why HABmin thinks that there is a myopenhab persistence. In myopenhab.persist I have written the sections strategies and items, but no items in it. For me it is no longer urgent, but if you want to dive in, we could make an appointment for a TeamViewer session. I used that before to support my brother.

 

Van: Chris Jackson [mailto:notifications@github.com] 
Verzonden: woensdag 14 januari 2015 22:24
Aan: cdjackson/HABmin
CC: GertKonemann
Onderwerp: Re: [HABmin] Opening HABmin generates hundreds of errors in the openHAB log (#206)

 

Hi Gert,
It's a bit difficult to explain I think :( One option if you like is I could remotely connect to your computer - I did this last weekend using TeamViewer - I'd never used it before but someone using HABmin2 had an issue and suggested it and it worked really well...

If you're not too keen on that, I'll try and talk you through it, but it's maybe less simple - let me now what you'd prefer...

Chris

**Comment by cdjackson** [comment]
Thanks Gert
I think ill ask viktor if he can shed some light on this.  Maybe myopenhab registers itself as a persistence service for some reason.

Ill let you know but it seems this is likely an issue within the java side rather than the client side so teamviewer wont help.

Cheers
Chris


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: GertKonemann <notifications@github.com> </div><div>Date:15/01/2015  11:06  (GMT+00:00) </div><div>To: cdjackson/HABmin <HABmin@noreply.github.com> </div><div>Cc: Chris Jackson <chris@cd-jackson.com> </div><div>Subject: Re: [HABmin] Opening HABmin generates hundreds of errors in the
  openHAB log (#206) </div><div>
</div>Hi Chris, 



I have found a workaround for this problem. I have put a dummy myopenhab.persist file in \openhab\configurations\persistence and now the error messages are gone. I do not understand why HABmin thinks that there is a myopenhab persistence. In myopenhab.persist I have written the sections strategies and items, but no items in it. For me it is no longer urgent, but if you want to dive in, we could make an appointment for a TeamViewer session. I used that before to support my brother. 



Van: Chris Jackson [mailto:notifications@github.com] 
Verzonden: woensdag 14 januari 2015 22:24 
Aan: cdjackson/HABmin 
CC: GertKonemann 
Onderwerp: Re: [HABmin] Opening HABmin generates hundreds of errors in the openHAB log (#206) 



Hi Gert, 
It's a bit difficult to explain I think :( One option if you like is I could remotely connect to your computer - I did this last weekend using TeamViewer - I'd never used it before but someone using HABmin2 had an issue and suggested it and it worked really well... 

If you're not too keen on that, I'll try and talk you through it, but it's maybe less simple - let me now what you'd prefer... 

Chris

**Comment by trusk89** [comment]
Creating a blank myopenhab.persist worked for me too! Thanks

**Comment by tktreload** [comment]
i can second that. creating the dummy file solves the problem.

**Comment by teichsta** [comment]
some more discussion is ongoing here https://groups.google.com/forum/#!msg/openhab/e087zYUonVI/y5ayOr07fBMJ

**Comment by teichsta** [comment]
@belovictor @cdjackson this would be great being fixed for 1.7.1 (whereever we have to fix something)

**Comment by GertKonemann** [comment]
Now using openHAB 2.0. Not seen this problem with that.
