### ISSUE TITLE
Unable to load ZWave product file: 'ge/45604.xml

### ISSUE THREAD

**Issue by hdonis** [cdjackson/HABmin#222]
Hi Chris, 
I know you said you fixed this a couple of days ago but I'm still getting the error when i run the application. I get the feeling that I must have missed a step or mis-understood what file i needed to update in order to get this to work. 

1. I updated to your latest "org.openhab.binding.zwave-1.7.0-SNAPSHOT.jar" file that was posted a few days ago. 
2. I deleted all the node.xml files
3. I ran OpenHab and monitored the zwave.log

Was i supposed to updated something else? I'm currently using OpenHab 1.6.2......I tried using 1.7.0 but couldn't get the webapplication portion of it (http://localhost:8080/openhab.app?sitemap=6974#_0003) to show any devices.

**Comment by cdjackson** [comment]
It's possible that this isn't included in the habmin version - im not sure. It shoukd be in the cloudbeea version though.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: hdonis <notifications@github.com> </div><div>Date:26/02/2015  03:01  (GMT+00:00) </div><div>To: cdjackson/HABmin <HABmin@noreply.github.com> </div><div>Subject: [HABmin] Unable to load ZWave product file: 'ge/45604.xml (#222) </div><div>
</div>Hi Chris, 
I know you said you fixed this a couple of days ago but I'm still getting the error when i run the application. I get the feeling that I must have missed a step or mis-understood what file i needed to update in order to get this to work.

I updated to your latest "org.openhab.binding.zwave-1.7.0-SNAPSHOT.jar" file that was posted a few days ago.
I deleted all the node.xml files
I ran OpenHab and monitored the zwave.log
Was i supposed to updated something else? I'm currently using OpenHab 1.6.2......I tried using 1.7.0 but couldn't get the webapplication portion of it (http://localhost:8080/openhab.app?sitemap=6974#_0003) to show any devices.

**Comment by hdonis** [comment]
Thanks Chris. 

I updated my file to the Cloudbee version as you suggested and the problem when away. 

Unfortunately, now my Aeon Labs Smart Strip DSC11-ZWUS  are no longer recognized by Habmin. 

 Martin Naughton, in the Google Groups forums, has already created database entry. I guess it just has to be merged to the latest version.

**Comment by cdjackson** [comment]
Great -thanks for the info. If Martin has already created the files then he needs to create a pull request otherwise I can’t merge them… Maybe you can ask him?
