### ISSUE TITLE
Add Duwi remote 05445 to database

### ISSUE THREAD

**Issue by kuifje123** [cdjackson/HABmin#224]
Hi Chris, 

Could you add the above remote to the database.
Here's a link to the user manual:

http://www.uk-automation.co.uk/pdf/Duwiremote.pdf

**Comment by cdjackson** [comment]
I’ll need more information. Either the type/id that HABmin is currently displaying, and/or, this device in the pepper1 database…

**Comment by kuifje123** [comment]
Unfortunately the type and id are UNKNOWN in Habmin, and the device is missing in the pepper1 database. Any other way I can retrieve the type and id ?

**Comment by cdjackson** [comment]
No - it’s very strange that HABmin doesn’t know this - are you sure the switch is actually included properly?  Or - Maybe this is one of the Duwi switches that doesn’t work well with controllers as it doesn’t support the wakeup class, in which case the binding won’t be able to easily work with the device (there are a few Duwi switches like this - unfortunately - and they don’t work well as they’re not listening, and don’t support wakeup).

If it’s one of these devices, then you can try restarting the binding, and then pressing the button on the switch every second or two for maybe 30 seconds while the binding starts to see if HABmin shows anything.  Otherwise, do the above, but send me the debug log and I’ll take a look to see if there’s anything I can do or see...

**Comment by kuifje123** [comment]
I tried your suggestion, however type and id remain unknown. I just found that this Duwi device is now sold by Z-wave.me brand and is included in pepper1 database:

http://pepper1.net/zwavedb/device/576

**Comment by kuifje123** [comment]
Even found the original Duwi device in the database:

http://pepper1.net/zwavedb/device/36

Hope you can add this one, thanks!

**Comment by cdjackson** [comment]
I can add it, but it won’t help since the binding can’t talk to the device it seems…

I assume you tried triple pressing the all on/off button?

The newer version looks like it might be better supported as it supports the wakeup class - the old one supports very little...

**Comment by cdjackson** [comment]
This device is already in the database - it was added about 8 months ago.

**Comment by kuifje123** [comment]
I was not able to get the duwi to work, I returned and bought the Zwave.me version which works out of the box.
